[FEAT] 게임 인트로의 플레이어 컨트롤러 및 위젯 제작
Scarecrow37/TempNameProject pull request #20
Opened 2024-01-26 01:32 UTC by ozcantsleep

### PR 타입
- [x] 기능 추가

### 반영 브랜치
plugin_launcher_feature_intro -> plugin_launcher

### 변경 사항
- 게임 인트로의 플레이어 컨트롤러 및 위젯 제작 (PM 요청으로 플러그인 X)

### 테스트 결과
- 테스트 결과 이상 없습니다.

2024-01-26 01:59 UTC, Scarecrow37 requested changes
Plugin에 Source 넣어주세요.

2024-01-26 04:27 UTC, Scarecrow37 requested changes
Java Doc 작성해주세요.

2024-01-26 04:27 UTC, Scarecrow37 commented on WWH_IntroScreen002/Packages/IntroPlugin/Source/IntroPlugin/Public/IntroUserWidget.h
> +	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "[Custom]VideoOptions")
JAVA Doc 해주세요

2024-01-26 08:54 UTC, ozcantsleep commented
- JavaDoc 작성.
- 인트로 화면이 끝났을때, 화면이 넘어가지 않는 버그를 잡기 위해, Delay 추가.
- Open Source를 사용할때 영상이 바로 재생 되면서 영상이 플레이 되지 않는 버그를 잡기위해, Open Source Latent로 변경. 소스를 열때 딜레이 시간 추가.

2024-01-30 10:06 UTC, Scarecrow37 approved these changes
confirm

2024-01-30 10:39 UTC, merged